name: gwc_customer_web
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
#  sdk: '>=3.2.2 <4.0.0'

  sdk: ">=2.16.2 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  flutter_emoji_feedback: any
  reviews_slider: ^2.0.0
  cupertino_icons: ^1.0.2

  easy_date_timeline: ^1.1.3
  crop_your_image: any

  #splash
  flutter_native_splash: ^2.4.1

#  device_preview: ^1.0.0
#  sizer: ^2.0.15
  convex_bottom_bar: ^3.0.0
  badges: ^3.1.2

  get: ^4.6.1
  flutter_svg: ^2.0.7
  date_picker_timeline: any
  file_picker: any
  rxdart: ^0.27.5
  lottie: ^2.6.0
  http: any
  platform_device_id: ^1.0.1
  slide_to_confirm: ^1.1.0
  dotted_border: ^2.0.0+2
  smooth_star_rating_null_safety: ^1.0.4+2
  smooth_page_indicator: ^1.0.0+2
  country_code_picker: any
  #  country_code_picker_mp: 1.0.0
  flutter_spinkit: ^5.1.0
  auto_orientation: any
  path_provider: any
  shared_preferences: any
  #  flutter_zoom_sdk: ^1.1.0+4
  im_animations: ^0.1.2
  syncfusion_flutter_pdfviewer: 22.2.12
  image_picker: ^1.0.7
  jwt_decode: ^0.3.1
  pip_view: ^0.9.7
  provider: any
  cached_network_image_web: any
  flutter_sim_country_code: any
  dropdown_button2: ^2.3.9
#  dropdown_button2: 1.9.2
#  firebase_core: any
#  firebase_core_platform_interface: any
#  firebase_messaging: any
  #  flutter_local_notifications: ^13.0.0
#  flutter_local_notifications: any

  #  ticket & chat
  grouped_list: any
  chatview: ^1.3.1
  pull_to_refresh_flutter3: ^2.0.1

  #  catcher: ^0.7.0
  mime: any
  photo_view: any
  circular_progress_bar_with_lines: ^0.0.5
  simple_circular_progress_bar: ^1.0.2
  vertical_percent_indicator: any
  url_launcher_web: any
  flutter_calendar_carousel: ^2.4.1
  readmore: any
  easy_scroll_to_index: any
  stories_for_flutter: ^1.2.0
  liquid_progress_indicator_v2: any
  crypto: any
  shimmer: any
  simple_tooltip: any
  pinput: any
  visibility_detector: any
  firebase_analytics: ^10.4.4
  #  new_version: ^0.3.1
  #  appinio_video_player: ^1.2.0
  wakelock_plus: any
  #  flutter_vlc_player: any
  image_cropper: any
  assets_audio_player: any
  tcard: ^1.3.5
  flutter_rating_bar: ^4.0.1
  syncfusion_flutter_gauges: 22.2.12
  chewie: any
  permission_handler: any
  carousel_slider: ^4.2.1
  flutter_horizontal_date_picker: any

  # internet checking
  internet_connection_checker: any
  connectivity_plus: any

  data_connection_checker_nulls: ^0.0.2
  flutter_ruler_picker: any
  syncfusion_flutter_charts: 22.2.12
  open_store: ^0.5.0
  syncfusion_flutter_datepicker: 22.2.12
  flutter_image_stack: any
  easy_stepper: any
  flutter_share_me: any
  flutter_widget_from_html: any

  #  for screenshot disable
  flutter_windowmanager: any
  lazy_loading_list: any
  flutter_sizer: ^1.0.5

  image_network: ^2.5.4+1
  flutter_pdfview: ^1.0.1

  percent_indicator: ^4.2.3

  date_format: any
  #  pdfx: ^2.4.0

  #home screens
  #  alarm: any
  flutter_inappwebview: any
#  webviewx: any

  just_audio: ^0.9.5
  audio_session: ^0.1.21
  audio_service: ^0.18.15

  pdf_to_image_converter: any
  razorpay_web: ^2.0.0

dependency_overrides:
  intl: any
  package_info_plus: any

#  change_app_package_name: ^1.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0
  flutter_launcher_icons: any

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/ic_launcher.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/lottie/
    - assets/images/notification/
    - assets/images/dashboard_stages/
    - assets/images/gmg/
    - assets/images/new_ds/
    - assets/images/faq/
    - assets/images/help_screens/
    - assets/images/gut_health_tracker/
    - assets/images/video_thumbnail/
    - assets/logo_gif/
  #   - images/a_dot_ham.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:

    - family: SensaBrush
      fonts:
        - asset: assets/font/SensaBrush.otf

    - family: GothamMedium
      fonts:
        - asset: assets/font/Gotham Medium.otf

    - family: GothamBook
      fonts:
        - asset: assets/font/Gotham Book.otf

    - family: GothamLight
      fonts:
        - asset: assets/font/Gotham-Light.otf

    - family: GothamRoundedBold
      fonts:
        - asset: assets/font/GothamRounded-Bold.otf

    - family: GothamBold
      fonts:
        - asset: assets/font/Gotham-Bold.otf

    - family: GothamRoundedBold_21016
      fonts:
        - asset: assets/font/GothamRoundedBold_21016.ttf

    - family: GothamBlack
      fonts:
        - asset: assets/font/Gotham-Black.otf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
