// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-uTAThB0HApccVpPj__XqlOb9_91-WAI',
    appId: '1:918707158642:web:e1e8e72c0d7dea429dcceb',
    messagingSenderId: '918707158642',
    projectId: 'assessment-2eda6',
    authDomain: 'assessment-2eda6.firebaseapp.com',
    storageBucket: 'assessment-2eda6.appspot.com',
    measurementId: 'G-XJTJNYNGVG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5gl3fJ9a_5iXYdb3xNB6IHGSw0g-MyeY',
    appId: '1:918707158642:android:13efdd150bc570949dcceb',
    messagingSenderId: '918707158642',
    projectId: 'assessment-2eda6',
    storageBucket: 'assessment-2eda6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC99iXvwJvSu4iKxJPRUbDGwZBUGbwQIXs',
    appId: '1:918707158642:ios:bd69efc9909233ec9dcceb',
    messagingSenderId: '918707158642',
    projectId: 'assessment-2eda6',
    storageBucket: 'assessment-2eda6.appspot.com',
    androidClientId: '918707158642-dvskrbvikh0cuii13h515nrlpf5akjrq.apps.googleusercontent.com',
    iosClientId: '918707158642-4qo2951p3sgah8bs8sgkkft8suvbnl3m.apps.googleusercontent.com',
    iosBundleId: 'com.example.gwcCustomerWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC99iXvwJvSu4iKxJPRUbDGwZBUGbwQIXs',
    appId: '1:918707158642:ios:2e77cd7cc39d06a19dcceb',
    messagingSenderId: '918707158642',
    projectId: 'assessment-2eda6',
    storageBucket: 'assessment-2eda6.appspot.com',
    androidClientId: '918707158642-dvskrbvikh0cuii13h515nrlpf5akjrq.apps.googleusercontent.com',
    iosClientId: '918707158642-b9asc1ug53rg5kudpp22cqtj9tvfkabj.apps.googleusercontent.com',
    iosBundleId: 'com.example.gwcCustomerWeb.RunnerTests',
  );
}
